sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: sh-cynosdbmysql-grp-j7caw66y.sql.tencentcdb.com
    port: 24148
    database: Xanadu
    username: root
    password: Hyf20021004

#    redis:
#      host: localhost
#      port: 6379
  #      password : 123456
  #      database: 10  数据源

  #阿里云
#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id:
#    access-key-secret:
#    bucket-name:
#
#  wechat:
#    appid:
#    secret:
